# Generated by Django 4.0.4 on 2022-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.FileField(upload_to='chats/'),
        ),
    ]
